Adds initial code
hdr-bgnn/drexel_metadata_formatter pull request #1
Opened 2022-10-26 19:17 UTC by johnbradley

Adds `dm_formatter.py` script containing @thibaulttabarin's Minnows specific metadata transformation code.
Adds a `Dockerfile` and GitHub Action config to build on release.
Adds a test script to exercise the metadata transformation code and GitHub Action config to run the tests.

2022-10-29 03:47 UTC, hlapp approved these changes
Comments and suggestions are all minor, so I'm approving in advance.

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +    BGNN_metadata version. Therefore some of the value not calcualted in drexel version are by
```suggestion
    BGNN_metadata version. Therefore some of the values not calculated in drexel version are by 
```

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +    defaulset to "None".
```suggestion
    default set to "None". 
```

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +    pixel_analysis = False if first_value['fish'][0]['pixel_analysis_failed'] else True
Wouldn't it be simpler to just use this assignment?
```suggestion
    pixel_analysis = !first_value['fish'][0]['pixel_analysis_failed']
```

2022-10-29 03:47 UTC, hlapp commented on Dockerfile
> +CMD echo "python dm_formatter.py [input] [output]"
This makes it look like input and output are optional, which it doesn't seem they actually are, and it also differs from the Usage section in the README.

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +    dict_fish = {'fish_num': fish_num,"bbox":fish_bbox,
```suggestion
    dict_fish = {'fish_num': fish_num,"bbox": fish_bbox, 
```

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +                 'pixel_analysis':pixel_analysis, 'rescale':"None",
```suggestion
                 'pixel_analysis': pixel_analysis, 'rescale': "None", 
```

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +                 'eye_bbox': "None", 'eye_center':eye_center , 'angle_degree': "None",
```suggestion
                 'eye_bbox': "None", 'eye_center': eye_center , 'angle_degree': "None",
```

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +                 'eye_direction':eye_direction, 'foreground_mean':round(foreground_mean,2),
```suggestion
                 'eye_direction': eye_direction, 'foreground_mean': round(foreground_mean,2), 
```

2022-10-29 03:47 UTC, hlapp commented on dm_formatter.py
> +                 'background_mean':round(background_mean,2)}
```suggestion
                 'background_mean': round(background_mean,2)}
```

2022-11-01 13:28 UTC, johnbradley commented on dm_formatter.py
> +    pixel_analysis = False if first_value['fish'][0]['pixel_analysis_failed'] else True
FYI: This should have been `pixel_analysis = not first_value['fish'][0]['pixel_analysis_failed']`.

2022-11-01 13:55 UTC, johnbradley commented
@thibaulttabarin Do you have any feedback for this PR?

2022-11-01 17:46 UTC, thibaulttabarin commented
> 

I didn't have time to do it throughly, it looks good but I want to test everything and i didn't have to finish to look at the drexel_metadata.

2022-11-02 23:19 UTC, thibaulttabarin requested changes
add 
#!/usr/bin/env python3

2022-11-02 23:20 UTC, thibaulttabarin requested changes
add 

# ADD scripts in /pipeline to the PATH
ENV PATH="/pipeline:${PATH}"

2022-11-03 13:39 UTC, johnbradley commented
@thibaulttabarin I added changes to put dm_formatter.py into the PATH and added the shebang.
If you have a metadata file named `INHS_FISH_74711_metadata.json` in the current directory you should be able to test out the changes like so:
```
docker build -t dmf .
docker run -v $(pwd):/data -it dmf dm_formatter.py /data/INHS_FISH_74711_metadata.json /data/result.json
```

2022-11-07 18:51 UTC, thibaulttabarin approved these changes

2022-11-07 18:51 UTC, merged